"""create slack user modal

Revision ID: aa555aeaf9e0
Revises: 
Create Date: 2025-12-15 16:01:49.862636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa555aeaf9e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slack_id', sa.String(), nullable=False),
    sa.Column('hrms_username', sa.String(), nullable=False),
    sa.Column('hrms_password', sa.String(), nullable=False),
    sa.Column('trigger_time', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_users_hrms_password'), 'slack_users', ['hrms_password'], unique=True)
    op.create_index(op.f('ix_slack_users_id'), 'slack_users', ['id'], unique=False)
    op.create_index(op.f('ix_slack_users_slack_id'), 'slack_users', ['slack_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_users_slack_id'), table_name='slack_users')
    op.drop_index(op.f('ix_slack_users_id'), table_name='slack_users')
    op.drop_index(op.f('ix_slack_users_hrms_password'), table_name='slack_users')
    op.drop_table('slack_users')
    # ### end Alembic commands ###
